=== davidrousse/david.rousse/cvxml/sourcesxml/xsd/cv.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
 Description : schema XML pour la validation d'un CV
 Auteur : David ROUSSE, d.rousse@wanadoo.fr
 Date derniere modification : 01/02/2003
-->
<xs:schema targetNamespace="http://perso.wanadoo.fr/david.rousse/" xmlns="http://perso.wanadoo.fr/david.rousse/" xmlns:drc="http://perso.wanadoo.fr/david.rousse/copyright/" xmlns:dr="http://perso.wanadoo.fr/david.rousse/" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<!-- Definition annotation (a titre informatif) -->
	<xs:annotation>
		<xs:documentation xml:lang="fr">
  Schéma XML pour la validation d'un CV, réalisé par David ROUSSE, d.rousse@wanadoo.fr.
 </xs:documentation>
	</xs:annotation>
	<!-- Importation d'un schema externe -->
	<xs:import namespace="http://perso.wanadoo.fr/david.rousse/copyright/" schemaLocation="dr_copyright.xsd"/>
	<!-- Definition type de donnees personnalise -->
	<xs:simpleType name="showType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="new"/>
			<xs:enumeration value="replace"/>
			<xs:enumeration value="embed"/>
			<xs:enumeration value="other"/>
			<xs:enumeration value="none"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- Definition element racine -->
	<xs:element name="cv">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dr:informations_cv" minOccurs="0"/>
				<xs:element ref="dr:etatcivil"/>
				<xs:element ref="dr:experiences_professionnelles"/>
				<xs:element ref="dr:formations"/>
				<xs:element ref="dr:connaissances"/>
				<xs:element ref="dr:divers"/>
				<xs:element ref="dr:informations_cv" minOccurs="0"/>
				<xs:element ref="dr:copyright"/>
			</xs:sequence>
			<xs:attribute name="langue" type="xs:language" use="required"/>
			<xs:attribute name="date_creation" type="xs:string" use="required"/>
			<xs:attribute name="date_mise_a_jour" type="xs:string" use="required"/>
			<xs:attribute name="titre" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<!-- Definition elements niveau (racine-1) -->
	<xs:element name="informations_cv">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dr:information" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="etatcivil">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dr:titre"/>
				<xs:element ref="dr:prenom"/>
				<xs:element ref="dr:nom"/>
				<xs:element ref="dr:adresse"/>
				<xs:element ref="dr:telephone"/>
				<xs:element ref="dr:email"/>
				<xs:element ref="dr:age"/>
				<xs:element ref="dr:etat_marital"/>
				<xs:element ref="dr:photo_identite" minOccurs="0"/>
				<xs:element ref="dr:information" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="formations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dr:titre"/>
				<xs:element ref="dr:formation" maxOccurs="unbounded"/>
				<xs:element ref="dr:information" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="connaissances">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dr:titre"/>
				<xs:element ref="dr:connaissance" maxOccurs="unbounded"/>
				<xs:element ref="dr:information" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="experiences_professionnelles">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dr:titre"/>
				<xs:element ref="dr:experience_professionnelle" maxOccurs="unbounded"/>
				<xs:element ref="dr:information" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="divers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dr:titre"/>
				<xs:element ref="dr:langues"/>
				<xs:element ref="dr:loisirs" minOccurs="0"/>
				<xs:element ref="dr:particularites" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="copyright">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="drc:dr_copyright"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- Definition elements niveau (racine-2) -->
	<xs:element name="formation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dr:date_debut"/>
				<xs:element ref="dr:date_fin" minOccurs="0"/>
				<xs:element ref="dr:description"/>
				<xs:element ref="dr:organisme"/>
				<xs:element ref="dr:ville"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="experience_professionnelle">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dr:date_debut"/>
				<xs:element ref="dr:date_fin" minOccurs="0"/>
				<xs:element ref="dr:description"/>
				<xs:element ref="dr:organisme"/>
				<xs:element ref="dr:ville"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="connaissance">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dr:domaine"/>
				<xs:element ref="dr:matiere" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="langues">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dr:langue" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- Definition elements niveau (racine-3) -->
	<xs:element name="langue">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dr:nom_langue"/>
				<xs:element ref="dr:niveau_langue"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="loisirs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dr:loisir" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="particularites">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dr:particularite" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="adresse">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dr:numero"/>
				<xs:element ref="dr:rue"/>
				<xs:element ref="dr:code_postal"/>
				<xs:element ref="dr:ville"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- Definition elements niveau (racine-4) -->
	<xs:element name="titre" type="xs:string"/>
	<xs:element name="prenom" type="xs:string"/>
	<xs:element name="nom" type="xs:string"/>
	<xs:element name="numero" type="xs:string"/>
	<xs:element name="rue" type="xs:string"/>
	<xs:element name="code_postal" type="xs:string"/>
	<xs:element name="ville" type="xs:string"/>
	<xs:element name="telephone" type="xs:string"/>
	<xs:element name="age" type="xs:string"/>
	<xs:element name="etat_marital" type="xs:string"/>
	<xs:element name="date_debut" type="xs:string"/>
	<xs:element name="date_fin" type="xs:string"/>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="organisme" type="xs:string"/>
	<xs:element name="domaine" type="xs:string"/>
	<xs:element name="matiere" type="xs:string"/>
	<xs:element name="nom_langue" type="xs:string"/>
	<xs:element name="niveau_langue" type="xs:string"/>
	<xs:element name="loisir" type="xs:string"/>
	<xs:element name="particularite" type="xs:string"/>
	<!-- Definition elements non vide avec attributs seuleument -->
	<xs:element name="information">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="show" type="showType"/>
					<xs:attribute name="type" type="xs:string" default="simple"/>
					<xs:attribute name="title" type="xs:string" use="required"/>
					<xs:attribute name="href" type="xs:string"/>
					<xs:attribute name="image" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="email">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="show" type="showType"/>
					<xs:attribute name="type" type="xs:string" fixed="simple"/>
					<xs:attribute name="title" type="xs:string" use="required"/>
					<xs:attribute name="href" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<!-- Definition elements vide avec attributs seuleument -->
	<xs:element name="photo_identite">
		<xs:complexType>
			<xs:attribute name="image" type="xs:string"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== davidrousse/david.rousse/cvxml/sourcesxml/xml/cv.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by King (MIAGe) -->
<dr:cv xmlns:dr="http://perso.wanadoo.fr/david.rousse/" xmlns:drc="http://perso.wanadoo.fr/david.rousse/copyright/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://perso.wanadoo.fr/david.rousse/ 
                        ../xsd/cv.xsd" langue="fr-CA" date_creation="12/02/2003" date_mise_a_jour="10/01/2004" titre="CV de David ROUSSE">
	<dr:informations_cv>
		<dr:information title="Page d'accueil du site de David ROUSSE" show="replace" type="simple" href="http://perso.wanadoo.fr/david.rousse/" image="sourcesxml/img/home.gif">
   Accueil
  </dr:information>
		<dr:information title="Téléchargement du CV au format PDF" show="replace" type="simple" href="cv.pdf" image="sourcesxml/img/download.gif">
   Télécharger le CV
  </dr:information>
	</dr:informations_cv>
	<dr:etatcivil>
		<dr:titre>Ingénieur d&apos;études au CNRS, Titulaire d&apos;un DESS MIAGe (Méthodes Informatiques Appliquées à la Gestion d&apos;Entreprise)</dr:titre>
		<dr:prenom>David</dr:prenom>
		<dr:nom>ROUSSE</dr:nom>
		<dr:adresse>
			<dr:numero>9</dr:numero>
			<dr:rue>chemin de Nabias</dr:rue>
			<dr:code_postal>65200</dr:code_postal>
			<dr:ville>ASTE</dr:ville>
		</dr:adresse>
		<dr:telephone>06.07.59.25.15</dr:telephone>
		<dr:email title="E-mail de David ROUSSE" show="new" type="simple" href="mailto:d.rousse@wanadoo.fr">
   d.rousse@wanadoo.fr
  </dr:email>
		<dr:age>26 ans</dr:age>
		<dr:etat_marital>Célibataire</dr:etat_marital>
		<dr:photo_identite image="sourcesxml/img/me.jpg"/>
		<dr:information title="David ROUSSE's resume" show="new" type="simple" href="http://perso.wanadoo.fr/david.rousse/resume.html" image="sourcesxml/img/uk.gif">English version</dr:information>
	</dr:etatcivil>
	<dr:experiences_professionnelles>
		<dr:titre>Expériences professionnelles</dr:titre>
		<dr:experience_professionnelle>
			<dr:date_debut>Sept. 2002</dr:date_debut>
			<dr:description>Ingénieur d&apos;études, Direction des Systèmes d&apos;Information</dr:description>
			<dr:organisme>CNRS</dr:organisme>
			<dr:ville>Toulouse</dr:ville>
		</dr:experience_professionnelle>
		<dr:experience_professionnelle>
			<dr:date_debut>Février 2002</dr:date_debut>
			<dr:date_fin>Juin 2002</dr:date_fin>
			<dr:description>Conception et mise en oeuvre sous SAP BW d&apos;un datawarehouse, avec SAP R/3 comme système source</dr:description>
			<dr:organisme>Airbus France</dr:organisme>
			<dr:ville>Toulouse</dr:ville>
		</dr:experience_professionnelle>
		<dr:experience_professionnelle>
			<dr:date_debut>Nov. 2001</dr:date_debut>
			<dr:date_fin>Déc. 2001</dr:date_fin>
			<dr:description>Panorama des technologies des réseaux sans fil (WPAN, WLAN, BLR, satellites, mobiles)</dr:description>
			<dr:organisme>IRIT</dr:organisme>
			<dr:ville>Toulouse</dr:ville>
		</dr:experience_professionnelle>
		<dr:experience_professionnelle>
			<dr:date_debut>Mai 2001</dr:date_debut>
			<dr:date_fin>Juin 2001</dr:date_fin>
			<dr:description>Modéliser une partie d&apos;un système d&apos;information avec UML et CORBA</dr:description>
			<dr:organisme>Société B&amp;T Associés</dr:organisme>
			<dr:ville>Toulouse</dr:ville>
		</dr:experience_professionnelle>
		<dr:experience_professionnelle>
			<dr:date_debut>Juin 2000</dr:date_debut>
			<dr:date_fin>Déc. 2000</dr:date_fin>
			<dr:description>Analyste - programmeur dans l&apos;architecture COM+, sur un progiciel de gestion de billetterie</dr:description>
			<dr:organisme>SSII CIMA</dr:organisme>
			<dr:ville>Pau</dr:ville>
		</dr:experience_professionnelle>
		<dr:experience_professionnelle>
			<dr:date_debut>Fév. 1999</dr:date_debut>
			<dr:date_fin>Mars 1999</dr:date_fin>
			<dr:description>Développement d&apos;un logiciel de paramétrage de coffret électrique par liaison série en Visual Basic</dr:description>
			<dr:organisme>SOULÉ</dr:organisme>
			<dr:ville>Bagnères de Bigorre</dr:ville>
		</dr:experience_professionnelle>
		<dr:experience_professionnelle>
			<dr:date_debut>Juin 1998</dr:date_debut>
			<dr:date_fin>Juin 1998</dr:date_fin>
			<dr:description>Création d&apos;un site Web, avec l&apos;écriture des pages HTML, des applets JAVA, d&apos;un script CGI</dr:description>
			<dr:organisme>SSII INFORADOUR - ADIX</dr:organisme>
			<dr:ville>Tarbes</dr:ville>
		</dr:experience_professionnelle>
		<dr:information title="Rapports de stage de David ROUSSE" show="new" type="simple" href="http://perso.wanadoo.fr/david.rousse/download_stages.html" image="sourcesxml/img/download.gif">Télécharger mes rapports de stage</dr:information>
	</dr:experiences_professionnelles>
	<dr:formations>
		<dr:titre>Formation</dr:titre>
		<dr:formation>
			<dr:date_debut>2001</dr:date_debut>
			<dr:date_fin>2002</dr:date_fin>
			<dr:description>DESS MIAGe, Mention Très Bien</dr:description>
			<dr:organisme>Université Paul Sabatier et Université des Sciences Sociales</dr:organisme>
			<dr:ville>Toulouse</dr:ville>
		</dr:formation>
		<dr:formation>
			<dr:date_debut>2000</dr:date_debut>
			<dr:date_fin>2001</dr:date_fin>
			<dr:description>Titre d&apos;ingénieur - maître, Mention Très Bien</dr:description>
			<dr:organisme>Université Paul Sabatier et Université des Sciences Sociales</dr:organisme>
			<dr:ville>Toulouse</dr:ville>
		</dr:formation>
		<dr:formation>
			<dr:date_debut>2000</dr:date_debut>
			<dr:date_fin>2001</dr:date_fin>
			<dr:description>Maîtrise MIAGe, Mention Bien</dr:description>
			<dr:organisme>Université Paul Sabatier et Université des Sciences Sociales</dr:organisme>
			<dr:ville>Toulouse</dr:ville>
		</dr:formation>
		<dr:formation>
			<dr:date_debut>1999</dr:date_debut>
			<dr:date_fin>2000</dr:date_fin>
			<dr:description>Licence MIAGe, Mention Très Bien</dr:description>
			<dr:organisme>Université Paul Sabatier et Université des Sciences Sociales</dr:organisme>
			<dr:ville>Toulouse</dr:ville>
		</dr:formation>
		<dr:formation>
			<dr:date_debut>1997</dr:date_debut>
			<dr:date_fin>1999</dr:date_fin>
			<dr:description>B.T.S. Informatique de Gestion, Major académique</dr:description>
			<dr:organisme>Lycée Saint John Perse</dr:organisme>
			<dr:ville>Pau</dr:ville>
		</dr:formation>
		<dr:formation>
			<dr:date_debut>1995</dr:date_debut>
			<dr:date_fin>1997</dr:date_fin>
			<dr:description>Mathématiques - Supérieures, Enseignement par correspondance</dr:description>
			<dr:organisme>C.N.E.D.</dr:organisme>
			<dr:ville>Tarbes</dr:ville>
		</dr:formation>
		<dr:formation>
			<dr:date_debut>1994</dr:date_debut>
			<dr:date_fin>1995</dr:date_fin>
			<dr:description>Baccalauréat série S, Mention Assez Bien</dr:description>
			<dr:organisme>Lycée Victor - Duruy</dr:organisme>
			<dr:ville>Bagnères de Bigorre</dr:ville>
		</dr:formation>
	</dr:formations>
	<dr:connaissances>
		<dr:titre>Connaissances</dr:titre>
		<dr:connaissance>
			<dr:domaine>Analyse et conception</dr:domaine>
			<dr:matiere>Méthode MERISE</dr:matiere>
			<dr:matiere>Langage de modélisation UML</dr:matiere>
		</dr:connaissance>
		<dr:connaissance>
			<dr:domaine>Architectures réparties</dr:domaine>
			<dr:matiere>SOAP</dr:matiere>
			<dr:matiere>CORBA</dr:matiere>
			<dr:matiere>RMI</dr:matiere>
			<dr:matiere>COM+</dr:matiere>
		</dr:connaissance>
		<dr:connaissance>
			<dr:domaine>Base de données</dr:domaine>
			<dr:matiere>Oracle</dr:matiere>
			<dr:matiere>SQL Server</dr:matiere>
			<dr:matiere>relationnel</dr:matiere>
			<dr:matiere>répartie</dr:matiere>
			<dr:matiere>objet</dr:matiere>
		</dr:connaissance>
		<dr:connaissance>
			<dr:domaine>Programmation</dr:domaine>
			<dr:matiere>C</dr:matiere>
			<dr:matiere>C++</dr:matiere>
			<dr:matiere>Java</dr:matiere>
			<dr:matiere>Visual Basic</dr:matiere>
			<dr:matiere>COBOL</dr:matiere>
			<dr:matiere>Prolog</dr:matiere>
		</dr:connaissance>
		<dr:connaissance>
			<dr:domaine>Réseaux</dr:domaine>
			<dr:matiere>Modèle OSI</dr:matiere>
			<dr:matiere>Architecture TCP/IP</dr:matiere>
			<dr:matiere>Sécurité</dr:matiere>
			<dr:matiere>Sans fil</dr:matiere>
		</dr:connaissance>
		<dr:connaissance>
			<dr:domaine>Technologies Internet</dr:domaine>
			<dr:matiere>XML</dr:matiere>
			<dr:matiere>XSLT</dr:matiere>
			<dr:matiere>XSL-FO</dr:matiere>
			<dr:matiere>ASP</dr:matiere>
		</dr:connaissance>
		<dr:connaissance>
			<dr:domaine>EAI</dr:domaine>
			<dr:matiere>webMethods</dr:matiere>
			<dr:matiere>Sunopsys</dr:matiere>
			<dr:matiere>Insevo eIntegration</dr:matiere>
		</dr:connaissance>
		<dr:connaissance>
			<dr:domaine>EDI</dr:domaine>
			<dr:matiere>Axway CFT</dr:matiere>
			<dr:matiere>SAGE Banque Paiement 500</dr:matiere>
		</dr:connaissance>
		<dr:connaissance>
			<dr:domaine>SI décisionnel</dr:domaine>
			<dr:matiere>Oracle Warehouse Builder</dr:matiere>
			<dr:matiere>SAP BW</dr:matiere>
		</dr:connaissance>
		<dr:connaissance>
			<dr:domaine>Gestion d&apos;entreprise</dr:domaine>
			<dr:matiere>Finance et comptabilité</dr:matiere>
			<dr:matiere>Gestion des processus</dr:matiere>
			<dr:matiere>Approche qualité</dr:matiere>
			<dr:matiere>Concept d&apos;ERP</dr:matiere>
		</dr:connaissance>
	</dr:connaissances>
	<dr:divers>
		<dr:titre>Divers</dr:titre>
		<dr:langues>
			<dr:langue>
				<dr:nom_langue>Français</dr:nom_langue>
				<dr:niveau_langue>Langue maternelle</dr:niveau_langue>
			</dr:langue>
			<dr:langue>
				<dr:nom_langue>Anglais</dr:nom_langue>
				<dr:niveau_langue>Bon</dr:niveau_langue>
			</dr:langue>
			<dr:langue>
				<dr:nom_langue>Espagnol</dr:nom_langue>
				<dr:niveau_langue>Scolaire</dr:niveau_langue>
			</dr:langue>
		</dr:langues>
		<dr:loisirs>
			<dr:loisir>Lecture</dr:loisir>
			<dr:loisir>Cinéma</dr:loisir>
			<dr:loisir>Jeux vidéo</dr:loisir>
			<dr:loisir>Amateur de rugby</dr:loisir>
			<dr:loisir>Lecture</dr:loisir>
		</dr:loisirs>
		<dr:particularites>
			<dr:particularite>Reconnaissance COTOREP travailleur handicapé catégorie C</dr:particularite>
		</dr:particularites>
	</dr:divers>
